# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.11.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    defaults:
      run:
        working-directory: ./healthyMeal
    
    steps:
      # {1} Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v4
      
      # {2} Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./healthyMeal/package-lock.json
      
      # {3} Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # {4} Run tests
      - name: Run tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      
      # {5} Build
      - name: Build
        run: npm run build
